#!/usr/bin/env python3
"""Render the same topology as a Mermaid flowchart.

Part of the Topology Cartographer skill (Phase 4: render).

The `.drawio` file is the primary artefact, but it needs the
hediet.vscode-drawio extension to be visible. The Mermaid version costs almost
nothing and renders inline in any Markdown preview, in a pull-request
description, and in chat surfaces that cannot show a file from disk - which is
exactly the situation in GitHub Copilot Chat before the file is opened.

Same content, same evidence distinction: a solid arrow is `[CODE]`, a dotted
arrow is `[INFERENCE]` or `[UNVERIFIED]`.

Usage
-----
    python3 render_mermaid.py service-topology/graph-model.laid-out.json \
        -o service-topology/master-topology.mmd
    python3 render_mermaid.py graph-model.json --service orders-svc \
        -o service-topology/micro/orders-svc.mmd
    python3 render_mermaid.py graph-model.json --mode all --output-dir service-topology
    python3 render_mermaid.py graph-model.json --fenced   # ```mermaid block
    python3 render_mermaid.py --example

Exit codes
----------
    0  diagram(s) written
    1  bad arguments or unreadable input
    2  the named service is not in the model
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import List, Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from topology_lib.model import (  # noqa: E402
    GraphModel,
    OutsideOutputRoot,
    SafeWriter,
    subgraph_for_service,
    user_path,
)
from topology_lib.render import render_mermaid  # noqa: E402
from topology_lib.theme import THEME_NAMES  # noqa: E402
from topology_lib.textutil import safe_filename  # noqa: E402

EXAMPLE = """\
%% Master topology
%% Generated by topology-cartographer 1.0.0 - do not edit by hand.
%% Solid arrow = [CODE] (read directly). Dotted arrow = [INFERENCE]/[UNVERIFIED].
flowchart LR
  n0["orders-svc"]
  n1{{"orders.created"}}
  n2["billing-svc"]
  n3[("PostgreSQL<br/>orders")]

  n0 -->|"key=order_id"| n1
  n1 -->|"group=billing"| n2
  n2 -.->|"GetOrder"| n0
  n0 -->|"orders"| n3

  classDef service fill:#dae8fc,stroke:#6c8ebf,color:#10314f;
  classDef topic fill:#ffe6cc,stroke:#d79b00,color:#653700;
  classDef datastore fill:#d5e8d4,stroke:#82b366,color:#1f3d18;
  class n0,n2 service;
  class n1 topic;
  class n3 datastore;
"""


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="render_mermaid.py",
        description="Render a graph model as a Mermaid flowchart.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Mermaid needs no layout block - it lays itself out - so this\n"
               "script accepts graph-model.json directly.\n",
    )
    parser.add_argument("model", nargs="?", help="path to a graph model")
    parser.add_argument(
        "--mode", choices=("master", "micro", "all"), default="master",
        help="master (default), micro (needs --service), or all")
    parser.add_argument("--service", help="service id, required for --mode micro")
    parser.add_argument("-o", "--output", help="output file for master/micro mode")
    parser.add_argument(
        "--output-dir", default="service-topology",
        help="directory for --mode all (default: service-topology)")
    parser.add_argument(
        "--output-root", default="service-topology",
        help="containment root; nothing is written outside it")
    parser.add_argument(
        "--theme", choices=THEME_NAMES, default=None,
        help="node shapes; defaults to the theme the model was laid out "
             "under, so the .mmd and the .drawio read as one diagram")
    parser.add_argument(
        "--no-master", action="store_true",
        help="with --mode all, render only the micro topologies - the same "
             "rule render_drawio.py follows, so the two stay in step")
    parser.add_argument(
        "--fenced", action="store_true",
        help="wrap the output in a ```mermaid fence, ready to paste into chat")
    parser.add_argument(
        "--example", action="store_true",
        help="print an example Mermaid flowchart and exit")
    return parser.parse_args(argv)


def fence(text: str, fenced: bool) -> str:
    return "```mermaid\n{0}```\n".format(text) if fenced else text


def micro_targets(model: GraphModel) -> List[str]:
    """Services worth a micro topology.

    The same rule `layout_graph.py` applies, so the two renderers produce the
    same set of files: a service known only because something calls it has no
    inside to draw, and its micro topology would be the one arrow that named it.
    """
    return sorted(
        service_id for service_id, node in model.services.items()
        if dict(node.attributes).get("origin") != "referenced-only")


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)

    if args.example:
        sys.stdout.write(EXAMPLE)
        return 0
    if not args.model:
        print("error: a graph model path is required (or use --example)",
              file=sys.stderr)
        return 1

    try:
        model = GraphModel.load(str(Path(args.model).expanduser()))
    except (OSError, IOError) as error:
        print("error: {0}".format(error), file=sys.stderr)
        return 1
    except ValueError as error:
        print("error: {0} is not valid JSON: {1}".format(args.model, error),
              file=sys.stderr)
        return 1

    writer = SafeWriter(user_path(args.output_root))
    # A subgraph is a fresh model with no layout block of its own, so the
    # theme is resolved once here and passed down rather than re-read per call.
    theme = args.theme or model.layout.get("theme")

    try:
        if args.mode == "all":
            if not args.no_master:
                master = render_mermaid(model, "Master topology", theme=theme)
                target = writer.write_text(
                    user_path(str(Path(args.output_dir) / "master-topology.mmd")),
                    fence(master, args.fenced))
                print("wrote {0}".format(target))
            for service_id in micro_targets(model):
                text = render_mermaid(
                    subgraph_for_service(model, service_id),
                    "Micro topology - {0}".format(model.services[service_id].display),
                    theme=theme)
                relative = "micro/{0}.mmd".format(safe_filename(service_id))
                target = writer.write_text(
                    user_path(str(Path(args.output_dir) / relative)), fence(text, args.fenced))
                print("wrote {0}".format(target))
            return 0

        if args.mode == "micro" or args.service:
            if not args.service:
                print("error: --mode micro requires --service", file=sys.stderr)
                return 1
            if args.service not in model.services:
                print("error: no service {0!r} in this model. Known: {1}".format(
                    args.service, ", ".join(sorted(model.services)) or "(none)"),
                    file=sys.stderr)
                return 2
            text = render_mermaid(
                subgraph_for_service(model, args.service),
                "Micro topology - {0}".format(model.services[args.service].display),
                theme=theme)
        else:
            text = render_mermaid(model, "Master topology", theme=theme)

        payload = fence(text, args.fenced)
        if args.output:
            target = writer.write_text(user_path(args.output), payload)
            print("wrote {0}".format(target))
        else:
            sys.stdout.write(payload)
    except OutsideOutputRoot as error:
        print("error: {0}".format(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
